name: Load Test
on: [push]
jobs:
  k6_performance_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run k6 test
      uses: k6io/action@v0.1
      with:
        filename: performance/load_test.ts