name: CI Demoblaze Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ui-acceptance-tests:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.42.0  # Official image with pre-installed browsers
    defaults:
      run:
        working-directory: ui
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npm run ui:acceptance
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-acceptance
          path: ui/playwright-report/
          retention-days: 30

  ui-accessibility-tests:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.42.0
    defaults:
      run:
        working-directory: ui
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npm run ui:accessibility
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-accessibility
          path: ui/playwright-report/
          retention-days: 30

  ui-regression-tests:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.42.0
    defaults:
      run:
        working-directory: ui
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npm run ui:regression
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-regression
          path: ui/playwright-report/
          retention-days: 30