name: Visual Testing

on:
  push:
    branches:
      [main, master]
  pull_request:
    branches: [main, master]

jobs:
  # Job to Upload Initial Baseline Images (Manual)
  upload_baseline_images:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run visual regression
        run: npm run visual --ignore-snapshots exit 0
        
      - name: Upload Baseline Images
        uses: actions/upload-artifact@v3
        with:
          name: baseline-images
          path: ./tests/visual_check_home_page.spec.ts-snapshots
      
      - name: Always Pass the First Job
        run: exit 0

  # Job to Run Visual Validation Tests (CI Validation)
  visual_validation:
    runs-on: ubuntu-latest
    needs: upload_baseline_images

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install # or yarn install

      - name: Download Baseline Images
        uses: actions/download-artifact@v3
        with:
          name: baseline-images
          path: ./tests/visual_check_home_page.spec.ts-snapshots

      - name: Run Visual Validation Tests
        run: npm run visual
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
