name: Visual Testing

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  # Job to Upload Initial Baseline Images (Manual)
  upload_baseline_images:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.52.0  # Pre-installed browsers
    defaults:
      run:
        working-directory: ui
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Generate Baseline Images
        run: npm run ui:visual --ignore-snapshots || true
      - name: Upload Baseline Images
        uses: actions/upload-artifact@v4
        with:
          name: baseline-images
          path: ui/tests/visual/visual_check_home_page.spec.ts-snapshots

  # Job to Run Visual Validation Tests (CI Validation)
  visual_validation:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.52.0  # Same image for consistency
    defaults:
      run:
        working-directory: ui
    needs: upload_baseline_images
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Download Baseline Images
        uses: actions/download-artifact@v4
        with:
          name: baseline-images
          path: ui/tests/visual/visual_check_home_page.spec.ts-snapshots
      - name: Run Visual Validation Tests
        run: npm run ui:visual
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ui/playwright-report/
          retention-days: 30